import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

/**
 * Export BOQ data as Excel workbook
 */
export function exportExcel({ project, boqItems, vendorQuotes }) {
  const wb = XLSX.utils.book_new();

  // Sheet 1: Project Info
  const projectData = [
    ['Project Name', project?.project_name || ''],
    ['Type', project?.project_type || ''],
    ['Client', project?.client || ''],
    ['Location', project?.location || ''],
    ['Budget', project?.budget || 0],
    ['Status', project?.status || ''],
    ['Deadline', project?.deadline || ''],
    ['Generated', format(new Date(), 'dd MMM yyyy HH:mm')],
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(projectData), 'Project');

  // Sheet 2: BOQ Items
  if (boqItems?.length) {
    const boqHeaders = ['#', 'Description', 'Quantity', 'Unit', 'Rate', 'Amount', 'Category'];
    const boqRows = boqItems.map((item, i) => [
      i + 1,
      item.description || item.product || '',
      item.quantity || item.qty || 0,
      item.unit || '',
      item.rate || 0,
      item.amount || 0,
      item.category || '',
    ]);
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([boqHeaders, ...boqRows]), 'BOQ Items');
  }

  // Sheet 3: Vendor Quotes (if available)
  if (vendorQuotes?.length) {
    const quoteHeaders = ['Vendor', 'Total Amount', 'GST', 'Grand Total', 'Delivery (days)', 'Status'];
    const quoteRows = vendorQuotes.map(q => [
      q.vendor_name, q.total_amount || 0, q.gst_total || 0,
      q.grand_total || 0, q.delivery_days || '-', q.status || '',
    ]);
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([quoteHeaders, ...quoteRows]), 'Vendor Quotes');
  }

  const filename = `${(project?.project_name || 'FlyyyAI').replace(/[^a-zA-Z0-9]/g, '_')}_BOQ_Report.xlsx`;
  XLSX.writeFile(wb, filename);
}

/**
 * Export BOQ data as PDF report
 */
export function exportPDF({ project, boqItems, vendorQuotes }) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Cover page
  doc.setFillColor(37, 99, 235); // blue-600
  doc.rect(0, 0, pageWidth, 60, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('FlyyyAI', 20, 30);
  doc.setFontSize(10);
  doc.text('CONSTRUCTION INTELLIGENCE', 20, 38);

  doc.setTextColor(30, 41, 59); // slate-800
  doc.setFontSize(18);
  doc.text(project?.project_name || 'BOQ Report', 20, 80);

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139); // slate-500
  const info = [
    `Type: ${project?.project_type || '-'}`,
    `Client: ${project?.client || '-'}`,
    `Location: ${project?.location || '-'}`,
    `Budget: ${Number(project?.budget || 0).toLocaleString('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 })}`,
    `Status: ${project?.status || '-'}`,
    `Generated: ${format(new Date(), 'dd MMM yyyy')}`,
  ];
  info.forEach((line, i) => doc.text(line, 20, 95 + i * 8));

  // BOQ Items table
  if (boqItems?.length) {
    doc.addPage();
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text('BOQ Extracted Materials', 20, 20);

    doc.autoTable({
      startY: 28,
      head: [['#', 'Description', 'Qty', 'Unit', 'Rate', 'Amount', 'Category']],
      body: boqItems.map((item, i) => [
        i + 1,
        (item.description || item.product || '').substring(0, 50),
        item.quantity || item.qty || 0,
        item.unit || '',
        item.rate || 0,
        item.amount || 0,
        item.category || '',
      ]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [37, 99, 235], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });
  }

  // Vendor Quotes table
  if (vendorQuotes?.length) {
    doc.addPage();
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text('Vendor Quote Comparison', 20, 20);

    doc.autoTable({
      startY: 28,
      head: [['Vendor', 'Total', 'GST', 'Grand Total', 'Delivery', 'Status']],
      body: vendorQuotes.map(q => [
        q.vendor_name, q.total_amount || 0, q.gst_total || 0,
        q.grand_total || 0, q.delivery_days ? `${q.delivery_days} days` : '-', q.status || '',
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [37, 99, 235], textColor: 255 },
    });
  }

  // Footer on every page
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`${project?.project_name || 'FlyyyAI'} - Page ${i} of ${totalPages}`, 20, doc.internal.pageSize.getHeight() - 10);
    doc.text('Generated by FlyyyAI', pageWidth - 60, doc.internal.pageSize.getHeight() - 10);
  }

  const filename = `${(project?.project_name || 'FlyyyAI').replace(/[^a-zA-Z0-9]/g, '_')}_Report_${format(new Date(), 'yyyyMMdd')}.pdf`;
  doc.save(filename);
}
